### ISSUE TITLE
Bug: Last item has highlighted class on load

### ISSUE THREAD

**Issue by sandrooco** [eddiemf/vue-scrollactive#11] opened 2017-11-28 10:27 UTC
On page load the last item that has a binding receives the active class, which is wrong. When I scroll for just 1px it will be fixed. What's the problem?

`<scrollactive v-if="showNavText" active-class="router-link-exact-active" :offset="80" :duration="600">`
`    <a class="navigation-text-desktop scrollactive-item" href="#home">News</a>`
`    <a class="navigation-text-desktop scrollactive-item" href="#links">Links</a>`
`    <a class="navigation-text-desktop scrollactive-item" href="#community">Community</a>`
`</scrollactive>`

**Comment by eddiemf** [comment] 2017-11-28 14:41
That should not be happening, it might be something related to the way you structured your html/css maybe, can you provide a fiddle reproducing or maybe the website you're seeing the bug?

Thanks!

**Comment by sandrooco** [comment] 2017-11-28 14:57
Thanks for replying. The html is just as the upper, only a `header` which has `position: fixed;` is wrapped around it.
I can't really post a fiddle or the url of the app because it's an internal product. Are there any requirements that the html has to meet?

**Comment by eddiemf** [comment] 2017-11-28 15:27
I mean the HTML of your whole page, isn't `#home`, `#links` or `#community` being loaded dynamically or something like that? The class is added to the section you're currently in when page is loaded, so maybe the way your page is loading might be causing this wrong behavior.

The ideal scenario would be a structure like this with the header being fixed:

```
<header>
    <scrollactive class="my-nav">
        <a href="#home" class="scrollactive-item">Home</a>
        <a href="#about-us" class="scrollactive-item">About Us</a>
        <a href="#portfolio" class="scrollactive-item">Portfolio</a>
        <a href="#contact" class="scrollactive-item">Contact</a>
    </scrollactive>
</header>

<div id="home">
    // content here
</div>

<div id="about-us">
    // content here
</div>

<div id="portfolio">
    // content here
</div>

<div id="contact">
    // content here
</div>
```

Try to see if you're not doing anything that might be making the plugin think you are in the last section and not in the first one, also take a look in the repository example to see if that helps.

**Comment by sandrooco** [comment] 2017-11-29 08:02
Might this be the problem:
`<home></home>`
`<community-Links></community-Links>`
`<community></community>`

All of these components have a `section` tag as root element which have the respective `id` attributes. (All the components are always displayed altogether!) Setting the `id` on the component itself didn't work either (`<home id="home"></home>`).

**Comment by eddiemf** [comment] 2017-11-29 14:35
That might be the problem, but I'll need to make apply some tests to try to reproduce it. I've never really tested using components as the sections, but it should be working. Anyways I'll probably test it tonight and try to improve or maybe come with an alternative solution.

Thanks for the feedback :)

**Comment by eddiemf** [comment] 2018-12-02 21:20
Well, after all this time I finally have time to maintain my libraries, and I've tested this properly and looks like it's working with components as in your example too.

I'll close this issue for now, but if you or someone else still have some problem with this feel free to open it and I'll be happy to help :)

**Closed by eddiemf** 2018-12-02 21:20 UTC
Labels: investigating
